server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:customer-test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  basic:
    enabled: false